### ISSUE TITLE
thought about production usage

### ISSUE THREAD

**Issue by Tochemey** [tommie/go-coopsched#1]
Hello @tommie, great work and very clean implementation. Do you think this can be used a production code?

**Comment by tommie** [comment]
It is an experimentation framework for a proof-of-concept for https://github.com/golang/go/issues/51071, so I'll make no claims about production worthiness.

Since it doesn't affect the actual Go scheduler, any goroutines that are not part of the coop scheduler could change/circumvent the intended effect. If the other goroutines only do some small I/O once in a while, perhaps that's okay. Other than that, the implementation is probably fine. :)

**Comment by Tochemey** [comment]
@tommie Thank you so much for the swift response. I appreciate it. closing the issue.
